spring:
  application:
    name: Notify

  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_db
    redis:
      host: localhost
      port: 6379

api:
  security:
    token:
      secret: ${JWT_SECRET}

  external:
    mailtrap:
      url: https://sandbox.api.mailtrap.io
      token: ${MAILTRAP_TOKEN}
      inbox-id: ${MAILTRAP_INBOX_ID}
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID}
      auth-token: ${TWILIO_AUTH_TOKEN}
      phone-number: ${TWILIO_PHONE_NUMBER}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs